<?php

$arr = [
    "Home",
    "About Us",
    "Blog",
    "FAQ",
    "Contact",
    "Sign In",
    "Sign Up",
    "Dashboard",
    "Escrow",
    "Make Escrow",
    "Add Your Contact",
    "My Escrow",
    "My Profile",
    "Profile Settings",
    "About Company",
    "Useful Links",
    "All Right Reserved.",
    "Subscribe",
    "Transaction",
    "Fund",
    "Add Fund",
    "Fund Log",
    "Payout",
    "Payout Now",
    "Payout Log",
    "Support Ticket",
    "2FA Security",
    "Logout",
    "You have no notifications",
    "Clear",
    "Recent Post",
    "Balance",
    "Total Deposit",
    "Total Payout",
    "Times",
    "Pending Escrow",
    "Rejected Escrow",
    "Payment Hold",
    "Completed Escrow",
    "Release Escrow",
    "Received Payment",
    "Disputed Amount",
    "Resolved Payment",
    "Title",
    "Invoice ID",
    "Amount",
    "Status",
    "Pending",
    "Rejected",
    "Hold",
    "Completed",
    "Disputed",
    "Resolved by Admin",
    "Justice Favor",
    "Report",
    "Report Now",
    "Reported By",
    "Rules",
    "Conversation",
    "Type your message",
    "Add Contact for future transaction",
    "Username, Email or Phone",
    "Add People",
    "Most Recent Opponents",
    "Accept Request",
    "Cancel Request",
    "Request Pending",
    "Unblock",
    "Blocked",
    "No contact in your list",
    "Step 1",
    "Step 2",
    "Step 3",
    "Step 4",
    "Job / Deal Title",
    "Job Title",
    "Explain Rules",
    "Type Here",
    "Previous",
    "Next",
    "How much for job?",
    "Enter Amount",
    "Invite a opponent",
    "Submit",
    "Please enter job title.",
    "Please explain to Explain Rules",
    "Please enter a valid amount for job",
    "Please select your opponent for invite.",
    "Details",
    "Accept / Reject",
    "Release",
    "Chat",
    "Subject",
    "Invoice Id",
    "Opponent Fullname",
    "Opponent Email",
    "Opponent Username",
    "Invited At",
    "Close",
    "Accept",
    "Reject",
    "Your Card Information",
    "Card Number",
    "Name On Your Card",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "SCAN TO SEND",
    "Please Pay",
    "To Get",
    "Pay Now",
    "Pay via Monnify",
    "Pending Payment",
    "Complete Payment",
    "Rejected Payment",
    "Search",
    "Transaction ID",
    "Gateway",
    "Charge",
    "Time",
    "Detail",
    "Complete",
    "Cancel",
    "No Data Found!",
    "Transactions",
    "Admin Feedback",
    "Payment Information",
    "Request Amount",
    "Charge Amount",
    "Total Payable",
    "Available Balance",
    "Confirm Now",
    "Image Update",
    "Profile Information",
    "Password Setting",
    "First Name",
    "Last Name",
    "Username",
    "Email Address",
    "Phone Number",
    "Preferred language",
    "Select Language",
    "Password",
    "Address",
    "Update User",
    "Current Password",
    "New Password",
    "Forget Password",
    "Confirm Password",
    "Update Password",
    "Reset Password",
    "Send Password Reset Link",
    "Don't have any account?",
    "Create Ticket",
    "Last Reply",
    "Action",
    "Open",
    "Answered",
    "Replied",
    "Closed",
    "Customer Reply",
    "Image Upload",
    "Upload File",
    "Reply",
    "Are you want to close ticket?",
    "Confirm",
    "All Payment",
    "Cancel Payment",
    "Search for Transaction ID",
    "Remark",
    "SL No.",
    "Remarks",
    "Two Factor Authenticator",
    "Deactive Two Factor",
    "Active Two Factor",
    "Google Authenticator",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, install the Google Authenticator application on your mobile device.",
    "DOWNLOAD APP",
    "Payment By",
    "Payable",
    "Email Verification",
    "Code",
    "Email Or Username",
    "Forgot password?",
    "Already have an account?",
    "Enter Code",
    "Didn\\'t get Code? Click to",
    "Resend code",
    "Updated Successfully.",
    "Password Changes successfully.",
    "Current password did not match",
    "Two Factor has been enabled.",
    "Two Factor has been disabled.",
    "Wrong Verification Code.",
    "Insufficient Balance For Withdraw.",
    "Insufficient Balance For Payout.",
    "Image could not be uploaded.",
    "Payout request Successfully Submitted. Wait For Confirmation.",
    "Insufficient Balance.",
    "Invalid opponent has been selected!",
    "Your request has been sent",
    "Request has been accepted.",
    "You are already connected.",
    "Request has been rejected",
    "You are not connected each other",
    "This user has been blocked.",
    "This user has been unblocked.",
    "Deal has been accepted.",
    "Deal has been rejected.",
    "Invalid Request!",
    "Payment has been released.",
    "Your report has been sent.",
    "Email verification code has been sent",
    "SMS verification code has been sent",
    "Sending Failed",
    "Email verification code is required",
    "Verification code didn't match!",
    "Wrong Verification Code",
    "Blog Details",
    "Contact Us",
    "Your Name",
    "Your Email",
    "Your Subject",
    "Message",
    "Send Message",
    "Transaction Limit"
];

return $arr;



